INSERT INTO external_reviews (
    platform_id,
    game_id,
    ingestion_run_id,
    source_review_id,
    source_review_key,
    review_type_id,
    author_name,
    is_recommended,
    score_raw,
    score_scale_id,
    language_code,
    review_text_raw,
    review_text_clean,
    reviewed_at,
    helpful_count,
    playtime_hours,
    source_meta_json,
    updated_at
)
SELECT
    x.platform_id,
    x.game_id,
    x.ingestion_run_id,
    x.source_review_id,
    x.source_review_key,
    x.review_type_id,
    x.author_name,
    x.is_recommended,
    x.score_raw,
    x.score_scale_id,
    x.language_code,
    x.review_text_raw,
    x.review_text_clean,
    x.reviewed_at,
    COALESCE(x.helpful_count, 0),
    x.playtime_hours,
    x.source_meta_json,
    now()
FROM jsonb_to_recordset($1::jsonb) AS x(
    platform_id bigint,
    game_id bigint,
    ingestion_run_id bigint,
    source_review_id text,
    source_review_key text,
    review_type_id bigint,
    author_name text,
    is_recommended boolean,
    score_raw text,
    score_scale_id bigint,
    language_code text,
    review_text_raw text,
    review_text_clean text,
    reviewed_at timestamptz,
    helpful_count integer,
    playtime_hours numeric,
    source_meta_json jsonb
)
ON CONFLICT (platform_id, game_id, source_review_key)
DO UPDATE SET
    ingestion_run_id = EXCLUDED.ingestion_run_id,
    source_review_id = COALESCE(EXCLUDED.source_review_id, external_reviews.source_review_id),
    review_type_id = EXCLUDED.review_type_id,
    author_name = EXCLUDED.author_name,
    is_recommended = EXCLUDED.is_recommended,
    score_raw = EXCLUDED.score_raw,
    score_scale_id = EXCLUDED.score_scale_id,
    language_code = EXCLUDED.language_code,
    review_text_raw = EXCLUDED.review_text_raw,
    review_text_clean = EXCLUDED.review_text_clean,
    reviewed_at = EXCLUDED.reviewed_at,
    helpful_count = EXCLUDED.helpful_count,
    playtime_hours = EXCLUDED.playtime_hours,
    source_meta_json = COALESCE(EXCLUDED.source_meta_json, external_reviews.source_meta_json),
    is_deleted = false,
    updated_at = now();
